### ISSUE TITLE
Provide an es5 version as well

### ISSUE THREAD

**Issue by NitsanBaleli** [Kurtz1993/idle-service#1]
Please provide the es5 version so developers dont have to change their tooling to require the package.
I get this error when trying to bulid for production:

`Unexpected token: name (IdleService)`

The project uses webpack 2.

Anything I can do to help push this ?

**Comment by NitsanBaleli** [comment]
managed to fix this for now with:
`{ test: /\.js$/, loader: 'babel-loader', include: [path.resolve('./src'), /node_modules\/idle-service/] },`
in
`webpack.config.js`

**Comment by Kurtz1993** [comment]
Thanks for your comment @NitsanBaleli I will provide an ES5 version of the package as well 😃

**Comment by Kurtz1993** [comment]
One little question, are you using `import`s in your project?

**Comment by NitsanBaleli** [comment]
Yes

**Comment by Kurtz1993** [comment]
I've just updated the package to v2.0.5 with the code built in ES5. Can you give it a try?

**Comment by NitsanBaleli** [comment]
@Kurtz1993 
Just tested it, works great.
Thank you very much for your work -)

**Comment by Kurtz1993** [comment]
Thanks for your feedback @NitsanBaleli . Closing the issue now.
